"""State and transition model for the simulated smart building."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from enum import IntEnum
from math import cos, pi, sin
from typing import Any, Mapping

import numpy as np

from src.envs.thermal_model import CO2Model, ThermalModel, ThermalStep


class HVACAction(IntEnum):
    """Discrete HVAC operating levels."""

    OFF = 0
    LOW = 1
    MEDIUM = 2
    HIGH = 3


@dataclass(frozen=True)
class BuildingState:
    """Observable state of the simulated building at one point in time."""

    indoor_temperature_c: float
    outdoor_temperature_c: float
    relative_humidity_pct: float
    occupancy: int
    co2_ppm: float
    electricity_price_per_kwh: float
    hour: float
    hvac_action: int
    step: int

    def as_dict(self) -> dict[str, float | int]:
        """Return a serialization-friendly state mapping."""

        return asdict(self)


@dataclass(frozen=True)
class BuildingTransition:
    """Physical and cost outputs generated by one HVAC decision."""

    energy_kwh: float
    electricity_cost: float
    thermal: ThermalStep
    previous_action: int
    action: int

    @property
    def switched(self) -> bool:
        return self.previous_action != self.action

    @property
    def switch_magnitude(self) -> int:
        return abs(self.action - self.previous_action)


class BuildingSimulator:
    """Deterministic-by-seed transition engine used by the Gym environment."""

    def __init__(self, config: Mapping[str, Any]) -> None:
        self.config = config
        simulation = config["simulation"]
        self.timestep_hours = float(simulation["timestep_minutes"]) / 60.0
        self.thermal_model = ThermalModel(config["building"], config["hvac"])
        self.co2_model = CO2Model(config["iaq"])
        self.electrical_power_kw = {
            int(action): float(power)
            for action, power in config["hvac"]["electrical_power_kw"].items()
        }

    def initial_state(self, rng: np.random.Generator) -> BuildingState:
        """Create the initial midnight state for an episode."""

        hour = 0.0
        return BuildingState(
            indoor_temperature_c=float(
                self.config["building"]["initial_indoor_temperature_c"]
            ),
            outdoor_temperature_c=self.outdoor_temperature(hour, rng),
            relative_humidity_pct=self.relative_humidity(hour, rng),
            occupancy=self.occupancy(hour),
            co2_ppm=float(self.config["iaq"]["initial_co2_ppm"]),
            electricity_price_per_kwh=self.electricity_price(hour),
            hour=hour,
            hvac_action=int(HVACAction.OFF),
            step=0,
        )

    def transition(
        self,
        state: BuildingState,
        action: int,
        rng: np.random.Generator,
    ) -> tuple[BuildingState, BuildingTransition]:
        """Apply an HVAC action and return the next state and interval outputs."""

        if action not in self.electrical_power_kw:
            raise ValueError(f"Unsupported HVAC action: {action}")

        thermal = self.thermal_model.step(
            indoor_temperature_c=state.indoor_temperature_c,
            outdoor_temperature_c=state.outdoor_temperature_c,
            occupancy=state.occupancy,
            action=action,
            solar_heat_kw=self.solar_heat_gain(state.hour),
            timestep_hours=self.timestep_hours,
        )
        next_co2 = self.co2_model.step(
            current_co2_ppm=state.co2_ppm,
            occupancy=state.occupancy,
            action=action,
            timestep_hours=self.timestep_hours,
        )

        energy_kwh = self.electrical_power_kw[action] * self.timestep_hours
        electricity_cost = energy_kwh * state.electricity_price_per_kwh
        next_step = state.step + 1
        next_hour = (next_step * self.timestep_hours) % 24.0

        next_state = BuildingState(
            indoor_temperature_c=thermal.indoor_temperature_c,
            outdoor_temperature_c=self.outdoor_temperature(next_hour, rng),
            relative_humidity_pct=self.relative_humidity(next_hour, rng),
            occupancy=self.occupancy(next_hour),
            co2_ppm=next_co2,
            electricity_price_per_kwh=self.electricity_price(next_hour),
            hour=next_hour,
            hvac_action=action,
            step=next_step,
        )
        result = BuildingTransition(
            energy_kwh=float(energy_kwh),
            electricity_cost=float(electricity_cost),
            thermal=thermal,
            previous_action=state.hvac_action,
            action=action,
        )
        return next_state, result

    def outdoor_temperature(
        self, hour: float, rng: np.random.Generator | None = None
    ) -> float:
        """Return a sinusoidal daily outdoor temperature with optional noise."""

        weather = self.config["weather"]
        low = float(weather["daily_low_c"])
        high = float(weather["daily_high_c"])
        midpoint = (low + high) / 2.0
        amplitude = (high - low) / 2.0
        peak_hour = float(weather["peak_hour"])
        temperature = midpoint + amplitude * cos(2.0 * pi * (hour - peak_hour) / 24.0)
        if rng is not None:
            temperature += float(rng.normal(0.0, float(weather["noise_std_c"])))
        return float(np.clip(temperature, -20.0, 60.0))

    def relative_humidity(
        self, hour: float, rng: np.random.Generator | None = None
    ) -> float:
        """Return a bounded humidity profile, highest during cooler hours."""

        weather = self.config["weather"]
        minimum = float(weather["relative_humidity_min_pct"])
        maximum = float(weather["relative_humidity_max_pct"])
        peak_hour = float(weather["peak_hour"])
        normalized_heat = (1.0 + cos(2.0 * pi * (hour - peak_hour) / 24.0)) / 2.0
        humidity = maximum - normalized_heat * (maximum - minimum)
        if rng is not None:
            humidity += float(
                rng.normal(0.0, float(weather.get("humidity_noise_std_pct", 0.0)))
            )
        return float(np.clip(humidity, 0.0, 100.0))

    def occupancy(self, hour: float) -> int:
        """Return a workday occupancy profile with smooth arrival/departure."""

        config = self.config["occupancy"]
        start = float(config["workday_start_hour"])
        end = float(config["workday_end_hour"])
        arrival = float(config["arrival_transition_hours"])
        departure = float(config["departure_transition_hours"])
        peak = float(config["capacity"]) * float(config["peak_fraction"])

        if hour < start or hour >= end:
            fraction = 0.0
        elif arrival > 0 and hour < start + arrival:
            fraction = (hour - start) / arrival
        elif departure > 0 and hour >= end - departure:
            fraction = (end - hour) / departure
        else:
            fraction = 1.0
        return int(round(max(0.0, peak * fraction)))

    def electricity_price(self, hour: float) -> float:
        """Return the configured time-of-use electricity rate."""

        energy = self.config["energy"]
        if float(energy["peak_start_hour"]) <= hour < float(energy["peak_end_hour"]):
            return float(energy["peak_price_per_kwh"])
        if (
            float(energy["shoulder_start_hour"])
            <= hour
            < float(energy["shoulder_end_hour"])
        ):
            return float(energy["shoulder_price_per_kwh"])
        return float(energy["off_peak_price_per_kwh"])

    def solar_heat_gain(self, hour: float) -> float:
        """Approximate solar heat gain from sunrise to sunset."""

        if not 6.0 <= hour <= 18.0:
            return 0.0
        peak_gain = float(self.config["building"]["solar_heat_gain_peak_kw"])
        return float(peak_gain * sin(pi * (hour - 6.0) / 12.0))
